### ISSUE TITLE
[FEAT] Allow custom daily_quota_gb for azurerm_log_analytics_workspace

### ISSUE THREAD

**Issue by mloskot** [claranet/terraform-azurerm-run#1]
### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, users of the logs submodule can only specify [retention_in_days](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace#retention_in_days):

https://github.com/claranet/terraform-azurerm-run/blob/d0a98ab25a7f46853f0fb369b8902fec94ee9d64/modules/logs/r-logs.tf#L10-L11

It would be very useful if value of [daily_quota_gb](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/log_analytics_workspace#daily_quota_gb) can also be adjusted.

### New or Affected Resource(s)/Data Source(s)

azurerm_log_analytics_workspace

### Potential Terraform Configuration

Addition of new variable

```hcl
variable "log_analytics_workspace_daily_quota_gb" {
  description = "The workspace daily quota for ingestion in GB. Defaults to -1 (unlimited)."
  type        = number
  default     = -1
}
```

will allow refined configuration like in this example:

```hcl
module "logs" {
  source  = "claranet/run/azurerm//modules/logs"
  version = "x.x.x"

  client_name    = var.client_name
  location       = module.azure_region.location
  location_short = module.azure_region.location_short
  environment    = var.environment
  stack          = var.stack

  resource_group_name = module.rg.resource_group_name

  log_analytics_workspace_sku               = "PerGB2018"
  log_analytics_workspace_retention_in_days = 30  # Minimum for PerGB2018
  log_analytics_workspace_daily_quota_gb    = 0.5 # Based on legacy Free SKU default daily quota

  extra_tags = {
    foo = "bar"
  }
}
```

**Comment by mloskot** [comment]
If this idea is sensible, I can turn it into PR submission.

**Comment by Shr3ps** [comment]
Yeah, a PR would be nice! Thanks for your contrib

**Comment by mloskot** [comment]
Sure, done in #2
